server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3307/letscoding?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: dev
    password: 1234

<<<<<<< HEAD
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
=======
jpa:
  open-in-view: true
  hibernate:
    ddl-auto: create
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    format_sql: true
  show-sql: true
>>>>>>> 8880bc977ba99bac741ad07c5561bd88b9552c67

  security:
    user:
      name: test
      password: 1234